import {
  AnalyticsIcon,
  DashboardIcon,
  AddIcon,
  HelpIcon,
  AuthIcon,
  BlogIcon,
  PagesIcon,
  CalendarIcon,
  ChatSquareIcon,
  ChatSquare2Icon,
  ChatCircleIcon,
  ChatCircle2Icon,
  FAQIcon,
  EmailIcon,
  EditIcon,
  StorageIcon,
  HistoryIcon,
  UserIcon,
  HandTapIcon,
  AnimateUploadIcon,
  AnimateDownloadIcon,
  CheckIcon,
  WaitIcon,
  FigmaIcon,
  BehanceIcon,
  DribbbleIcon,
  GitHubIcon,
  CodepenIcon,
  QuoraIcon,
  InstagramIcon,
  FacebookIcon,
  LinkedinIcon,
  TwitterIcon,
  ThreadsIcon,
  SnapchatIcon,
  WhatsappIcon,
  GoogleIcon,
  YoutubeIcon,
  TelegramIcon,
  WechatIcon,
  TiktokIcon,
  RedditIcon,
  DiscordIcon,
  TwitchIcon,
  VimeoIcon,
  PinterestIcon,
  NextdoorIcon,
  TumblrIcon,
  ChatgptIcon,
  GeminiIcon,
  CreativeMarketIcon,
  MediumIcon,
  BloggerIcon,
  SocialIcon,
  WorkIcon,
  WorkIcon2,
  NewsletterIcon,
  AnnouncementIcon,
  EventIcon,
  HeartIcon,
  StoreIcon,
  HireBieIcon,
  PeopleIcon,
  OrderIcon,
  PeopleAddIcon,
  PeopleErrorIcon,
  ReviewsIcon,
  ReportIcon,
  CertificationIcon,
  TaskIcon,
  StartUpIcon,
  SuccessIcon,
  FlagAdd,
} from "./icons";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const iconsMap = {
  Analytics: AnalyticsIcon,
  Dashboard: DashboardIcon,
  Add: AddIcon,
  Help: HelpIcon,
  Auth: AuthIcon,
  Blog: BlogIcon,
  Pages: PagesIcon,
  Calendar: CalendarIcon,
  ChatSquare: ChatSquareIcon,
  ChatSquare2: ChatSquare2Icon,
  ChatCircle: ChatCircleIcon,
  ChatCircle2: ChatCircle2Icon,
  FAQ: FAQIcon,
  Email: EmailIcon,
  Edit: EditIcon,
  Storage: StorageIcon,
  History: HistoryIcon,
  User: UserIcon,
  HandTap: HandTapIcon,
  AnimateUpload: AnimateUploadIcon,
  AnimateDownload: AnimateDownloadIcon,
  Check: CheckIcon,
  Wait: WaitIcon,
  Social: SocialIcon,
  Figma: FigmaIcon,
  Behance: BehanceIcon,
  Dribbble: DribbbleIcon,
  GitHub: GitHubIcon,
  CodePen: CodepenIcon,
  Quora: QuoraIcon,
  Instagram: InstagramIcon,
  Facebook: FacebookIcon,
  Linkedin: LinkedinIcon,
  Twitter: TwitterIcon,
  Threads: ThreadsIcon,
  Snapchat: SnapchatIcon,
  Whatsapp: WhatsappIcon,
  Google: GoogleIcon,
  Youtube: YoutubeIcon,
  Telegram: TelegramIcon,
  Wechat: WechatIcon,
  Tiktok: TiktokIcon,
  Reddit: RedditIcon,
  Discord: DiscordIcon,
  Twitch: TwitchIcon,
  Vimeo: VimeoIcon,
  Pinterest: PinterestIcon,
  Nextdoor: NextdoorIcon,
  Tumblr: TumblrIcon,
  Chatgpt: ChatgptIcon,
  Gemini: GeminiIcon,
  CreativeMarket: CreativeMarketIcon,
  Medium: MediumIcon,
  Blogger: BloggerIcon,
  Work: WorkIcon,
  Work2: WorkIcon2,
  Newsletter: NewsletterIcon,
  Announcement: AnnouncementIcon,
  Event: EventIcon,
  Heart: HeartIcon,
  Store: StoreIcon,
  Services: HireBieIcon,
  Sales: HireBieIcon,
  Order: OrderIcon,
  Employees: PeopleIcon,
  EmployAdd: PeopleAddIcon,
  OldEmployees: PeopleErrorIcon,
  Reviews: ReviewsIcon,
  Report: ReportIcon,
  Certification: CertificationIcon,
  Task: TaskIcon,
  StartUp: StartUpIcon,
  Success: SuccessIcon,
  FlagAdd: FlagAdd,
};
